# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-28 05:03
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0027_auto_20170928_0603'),
        ('assetmanager', '0005_remove_assetdocument_expiry_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='dashboard.baseModel')),
                ('status', models.CharField(choices=[('submitted', 'submitted'), ('in review', 'in review'), ('Open', 'Open'), ('Closed', 'Closed')], max_length=200)),
                ('application_date', models.DateField(auto_now_add=True)),
                ('amount', models.IntegerField()),
                ('preferred_payment_date', models.DateField()),
                ('method_of_payt', models.CharField(choices=[('Cash', 'Cash'), ('Bank', 'Bank')], max_length=20)),
                ('tenure', models.IntegerField(null=True)),
                ('tenure_qualifier', models.CharField(max_length=50)),
                ('issue_date', models.DateField(null=True)),
                ('payment_frequency', models.CharField(choices=[('daily', 'daily'), ('monthly', 'monthly'), ('quaterly', 'quaterly'), ('bi-annual', 'bi-annual'), ('yearly', 'yearly')], max_length=50)),
                ('fee', models.IntegerField(blank=True, null=True)),
                ('fee_charge_method', models.IntegerField(blank=True, choices=[('1', 'Deduct from principal balance'), ('2', 'Add the fee on top of the loan')], null=True)),
                ('bank_account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='loan_payment_account', to='dashboard.personAccount')),
                ('borrower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('collateral', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='loan_colateral', to='assetmanager.Asset')),
                ('loan_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.loanType')),
            ],
            bases=('dashboard.basemodel',),
        ),
    ]
