# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-15 08:18
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_address', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('zip', models.CharField(max_length=200)),
                ('state', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('fullname', models.CharField(max_length=200)),
                ('full_address', models.CharField(blank=True, max_length=200)),
                ('city', models.CharField(blank=True, max_length=200)),
                ('zip', models.CharField(blank=True, max_length=200)),
                ('state', models.CharField(blank=True, max_length=200)),
                ('phone', models.CharField(blank=True, max_length=200)),
                ('state_of_origin', models.CharField(blank=True, max_length=200)),
                ('lga', models.CharField(blank=True, max_length=200)),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], max_length=200)),
                ('dob', models.DateField(blank=True)),
                ('marital_status', models.CharField(blank=True, choices=[('single', 'Single'), ('married', 'Married')], max_length=200)),
                ('picture', models.CharField(blank=True, max_length=200)),
                ('bio', models.TextField(blank=True, max_length=200)),
                ('current_employer', models.CharField(blank=True, max_length=200)),
                ('current_salary', models.CharField(blank=True, max_length=200)),
                ('job_description', models.TextField(blank=True)),
                ('years_in_workplace', models.TextField(blank=True, max_length=100)),
                ('sate_of_origin', models.CharField(blank=True, max_length=200)),
                ('vehicles_owned', models.CharField(blank=True, max_length=200)),
                ('years_at_residence', models.CharField(blank=True, max_length=200)),
                ('residential_status', models.CharField(blank=True, choices=[('Owner', 'Owner'), ('Renting', 'Renting'), ('Staying with Parent', 'Staying with Parent')], max_length=200)),
                ('educational_status', models.CharField(blank=True, choices=[('Graduate', 'Graduate'), ('High School', 'High School'), ('Phd', 'Phd'), ('Masters', 'Masters')], max_length=200)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='branch_client', to='dashboard.Branch')),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('domain', models.CharField(max_length=200)),
                ('primary_color', models.CharField(choices=[('#ff000', 'red')], max_length=200)),
                ('website', models.URLField(max_length=500)),
                ('email', models.EmailField(max_length=254)),
                ('owner', models.CharField(max_length=200)),
                ('currency_type', models.CharField(default='NGN', max_length=10)),
                ('logo', models.CharField(help_text='require a 100 by 100 img size', max_length=200)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('updated_by', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_by_company', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('fullname', models.CharField(blank=True, max_length=200)),
                ('full_address', models.CharField(blank=True, max_length=200)),
                ('city', models.CharField(blank=True, max_length=200)),
                ('zip', models.CharField(blank=True, max_length=200)),
                ('state', models.CharField(blank=True, max_length=200)),
                ('phone', models.CharField(blank=True, max_length=200)),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], max_length=200)),
                ('dob', models.DateField(blank=True)),
                ('state_of_origin', models.CharField(blank=True, max_length=200)),
                ('lga', models.CharField(blank=True, max_length=200)),
                ('marital_status', models.CharField(blank=True, choices=[('single', 'Single'), ('married', 'Married')], max_length=200)),
                ('picture', models.CharField(blank=True, max_length=200)),
                ('bio', models.TextField(blank=True, max_length=200)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('educational_status', models.CharField(blank=True, choices=[('Graduate', 'Graduate'), ('High School', 'High School'), ('Phd', 'Phd'), ('Masters', 'Masters')], max_length=200)),
                ('branch', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee_branch', to='dashboard.Branch')),
                ('company', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee_company', to='dashboard.Company')),
                ('created_by', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_by_on_employee', to=settings.AUTH_USER_MODEL)),
                ('manager', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee_manager', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='updated_by_employee', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employee', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='client',
            name='company',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='client_company', to='dashboard.Company'),
        ),
        migrations.AddField(
            model_name='client',
            name='created_by',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_by_on_client', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='client',
            name='laon_officer',
            field=models.ForeignKey(blank=True, help_text='Someone who manages the client among your staffs', on_delete=django.db.models.deletion.CASCADE, related_name='loan_officer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='client',
            name='updated_by',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='updated_by_client', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='client',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='client', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='branch',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Company'),
        ),
        migrations.AddField(
            model_name='branch',
            name='created_by',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_by_on_branch', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='branch',
            name='manager',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='branch_manager', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='branch',
            name='updated_by',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='updated_by_branch', to=settings.AUTH_USER_MODEL),
        ),
    ]
