# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-15 09:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='picture',
            field=models.ImageField(blank=True, max_length=200, upload_to='clients/'),
        ),
        migrations.AlterField(
            model_name='company',
            name='currency_type',
            field=models.CharField(choices=[('NGN', 'NGN'), ('USD', 'USD')], default='NGN', max_length=10),
        ),
        migrations.AlterField(
            model_name='company',
            name='logo',
            field=models.ImageField(help_text='require a 100 by 100 img size', max_length=200, upload_to='logos/'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='picture',
            field=models.ImageField(blank=True, max_length=200, upload_to='employee/'),
        ),
    ]
