# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-15 11:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20170715_1034'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='dob',
        ),
    ]
