# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-22 11:13
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0012_auto_20170716_1334'),
    ]

    operations = [
        migrations.CreateModel(
            name='baseModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='dashboard.baseModel')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('expiry_date', models.DateField(null=True)),
                ('inspection_date', models.DateField(null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            bases=('dashboard.basemodel',),
        ),
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='dashboard.baseModel')),
                ('bank_name', models.CharField(max_length=50)),
                ('account_number', models.CharField(max_length=50, null=True)),
                ('account_type', models.CharField(choices=[('savings', 'Savings'), ('current', 'Current'), ('Dollar Account', 'Dollar Account')], max_length=50)),
            ],
            bases=('dashboard.basemodel',),
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='dashboard.baseModel')),
                ('status', models.CharField(choices=[('submitted', 'submitted'), ('in review', 'in review'), ('Open', 'Open'), ('Closed', 'Closed')], max_length=200)),
                ('application_date', models.DateField(auto_now_add=True)),
                ('amount', models.IntegerField()),
                ('tenure', models.IntegerField(help_text='In months')),
                ('preferred_payment_date', models.DateField()),
                ('method_of_payt', models.CharField(choices=[('Cash', 'Cash'), ('Bank', 'Bank')], max_length=20)),
                ('issue_date', models.DateField(null=True)),
                ('borrower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('collateral', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loan_colateral', to='dashboard.Asset')),
            ],
            bases=('dashboard.basemodel',),
        ),
        migrations.CreateModel(
            name='loanType',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='dashboard.baseModel')),
                ('name', models.CharField(max_length=50)),
                ('rate', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('need_collteral', models.BooleanField(help_text='does this type of Loan need Coollateral')),
                ('need_guarantor', models.BooleanField(help_text='does this type of loan need a gurantor')),
                ('payment_frequency', models.CharField(choices=[('daily', 'daily'), ('monthly', 'monthly'), ('quaterly', 'quaterly'), ('bi-annual', 'bi-annual'), ('yearly', 'yearly')], max_length=50)),
            ],
            bases=('dashboard.basemodel',),
        ),
        migrations.AddField(
            model_name='basemodel',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applicationbranch', to='dashboard.Branch'),
        ),
        migrations.AddField(
            model_name='basemodel',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applicationcompany', to='dashboard.Company'),
        ),
        migrations.AddField(
            model_name='basemodel',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='applicationcreator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='basemodel',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='applicationupdater', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='companyAccount',
            fields=[
                ('bank_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='dashboard.Bank')),
                ('description', models.TextField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_account', to='dashboard.Company')),
            ],
            bases=('dashboard.bank',),
        ),
        migrations.CreateModel(
            name='personAccount',
            fields=[
                ('bank_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='dashboard.Bank')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_bank', to=settings.AUTH_USER_MODEL)),
            ],
            bases=('dashboard.bank',),
        ),
        migrations.AddField(
            model_name='loan',
            name='loan_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.loanType'),
        ),
        migrations.AddField(
            model_name='loan',
            name='bank_account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='loan_payment_account', to='dashboard.personAccount'),
        ),
    ]
