# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-22 11:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_auto_20170722_1213'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='status',
            field=models.CharField(choices=[('submitted', 'submitted'), ('in review', 'in review'), ('Open', 'Open'), ('Closed', 'Closed')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='bank',
            name='account_type',
            field=models.CharField(choices=[('savings', 'Savings'), ('current', 'Current'), ('Dollar Account', 'Dollar Account'), ('Others', 'Others')], max_length=50),
        ),
    ]
