# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-22 12:05
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0014_auto_20170722_1226'),
    ]

    operations = [
        migrations.CreateModel(
            name='activityLog',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='dashboard.baseModel')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('description', models.CharField(max_length=200)),
                ('level', models.IntegerField()),
                ('initiator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            bases=('dashboard.basemodel',),
        ),
        migrations.CreateModel(
            name='Documents',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='dashboard.baseModel')),
                ('upload_date', models.DateField(auto_now_add=True)),
                ('document_type', models.CharField(max_length=200)),
                ('file', models.FileField(upload_to='documents/')),
            ],
            bases=('dashboard.basemodel',),
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='dashboard.baseModel')),
                ('subject', models.CharField(max_length=200)),
                ('messages', models.TextField()),
                ('sent_on', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('sent', 'sent'), ('received', 'received')], max_length=20)),
                ('sent_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_sender', to=settings.AUTH_USER_MODEL)),
                ('sent_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            bases=('dashboard.basemodel',),
        ),
    ]
