# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-23 01:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0015_activitylog_documents_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loan',
            name='tenure',
        ),
        migrations.AddField(
            model_name='loantype',
            name='tenure',
            field=models.IntegerField(help_text='Please write how long in months', null=True),
        ),
    ]
