# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-23 02:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0017_loan_market'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loan',
            name='market',
        ),
        migrations.AddField(
            model_name='loantype',
            name='market',
            field=models.CharField(choices=[('Enterpreneurs', 'Enterpreneurs'), ('White Collar Jobs', 'White Collar Jobs'), ('Students', 'Student'), ('General', 'General'), ('Others', 'Others')], help_text='these include the category of people who will be interested in this particular product', max_length=50, null=True),
        ),
    ]
