# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-24 00:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0018_auto_20170723_0329'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loantype',
            old_name='need_collteral',
            new_name='need_collateral',
        ),
    ]
