# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-24 01:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0019_auto_20170724_0155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basemodel',
            name='branch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='applicationbranch', to='dashboard.Branch'),
        ),
        migrations.AlterField(
            model_name='basemodel',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='applicationcompany', to='dashboard.Company'),
        ),
    ]
