# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-24 01:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0020_auto_20170724_0227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loantype',
            name='rate',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
