# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-25 04:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0021_auto_20170724_0242'),
    ]

    operations = [
        migrations.CreateModel(
            name='documentType',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='dashboard.baseModel')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
            ],
            bases=('dashboard.basemodel',),
        ),
        migrations.AddField(
            model_name='loantype',
            name='max_amount_allowed',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='loantype',
            name='min_amount_allowed',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='loantype',
            name='documents',
            field=models.ManyToManyField(help_text='Include documents that are needed here for this particular loan.. You can go to the document section to add or delete document', null=True, to='dashboard.documentType'),
        ),
    ]
