# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-27 01:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0022_auto_20170725_0537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loantype',
            name='max_amount_allowed',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='loantype',
            name='min_amount_allowed',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
