# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-27 22:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0023_auto_20170727_0252'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='basemodel_ptr',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='bank_account',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='basemodel_ptr',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='borrower',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='collateral',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='loan_type',
        ),
        migrations.DeleteModel(
            name='Asset',
        ),
        migrations.DeleteModel(
            name='Loan',
        ),
    ]
