# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-30 01:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0024_auto_20170727_2354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loantype',
            name='documents',
            field=models.ManyToManyField(help_text='Include documents that are needed here for this particular loan.. You can go to the document section to add or delete document', to='dashboard.documentType'),
        ),
    ]
