# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-28 05:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0026_auto_20170806_2118'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loantype',
            name='payment_frequency',
        ),
        migrations.RemoveField(
            model_name='loantype',
            name='tenure',
        ),
        migrations.AddField(
            model_name='loantype',
            name='interest_type',
            field=models.CharField(choices=[('Flat Rate', 'Flat Rate'), ('Reducing Balance', 'Reducing Balance')], default='Flat Rate', max_length=50),
        ),
    ]
