# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-27 22:54
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0024_auto_20170727_2354'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='dashboard.baseModel')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('expiry_date', models.DateField(null=True)),
                ('inspection_date', models.DateField(null=True)),
                ('status', models.CharField(choices=[('submitted', 'submitted'), ('in review', 'in review'), ('Open', 'Open'), ('Closed', 'Closed')], max_length=20, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            bases=('dashboard.basemodel',),
        ),
    ]
