# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-30 01:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assetmanager', '0003_assetdocument'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetdocument',
            name='document_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
