# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-30 12:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assetmanager', '0004_auto_20170730_0232'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assetdocument',
            name='expiry_date',
        ),
    ]
